### ISSUE TITLE
Problem compiling under Raspbian Wheezy with Chicken 4.7.0

### ISSUE THREAD

**Issue by paines** [caolan/raspberry-pi-gpio#1]
I am struggeling to compile your egg:
chicken 

```
pi@raspberrypi ~/projects/tmp/raspberry-pi-gpio $ sudo chicken-install
retrieving ...
checking platform for `raspberry-pi-gpio' ...
checking dependencies for `raspberry-pi-gpio' ...
install order:
("raspberry-pi-gpio")
installing raspberry-pi-gpio: ...
changing current directory to .
  /usr/bin/csi -bnq -setup-mode -e "(require-library setup-api)" -e "(import setup-api)" -e "(setup-error-handling)" -e "(extension-name-and-version '(\"raspberry-pi-gpio\" \"\"))" raspberry-pi-gpio.setup
  /usr/bin/csc -feature compiling-extension -setup-mode    -O2 -d1 -s raspberry-pi-gpio.scm -lwiringPi -Iinclude -j raspberry-pi-gpio

Warning: reference to possibly unbound identifier `d'

Error: module unresolved: raspberry-pi-gpio

Error: shell command terminated with non-zero exit status 256: /usr/bin/chicken raspberry-pi-gpio.scm -output-file raspberry-pi-gpio.c -dynamic -feature chicken-compile-shared -feature compiling-extension -setup-mode -optimize-level 2 -debug-level 1 -emit-import-library raspberry-pi-gpio

Error: shell command failed with nonzero exit status 256:

  /usr/bin/csc -feature compiling-extension -setup-mode    -O2 -d1 -s raspberry-pi-gpio.scm -lwiringPi -Iinclude -j raspberry-pi-gpio


Error: shell command terminated with nonzero exit code
17920
"/usr/bin/csi -bnq -setup-mode -e \"(require-library setup-api)\" -e \"(import s...
```

I also fiddled around with some parameters like setting -I and -L in the setup file to /usr/local where wiringPi was installed, but no success. Looking at the code didn't unveil anything special to me, what could be producing the "warning".

**Comment by caolan** [comment]
Hey, sorry for not spotting this. There has been a significant rewrite of the code recently by @0-8-15 . If you're still interested then I suggest giving it another try. I've used it on Raspbian myself.

I'm going to close this ticket for now, feel free to re-open if you run into issues. If you do need to report a bug, please report the version of CHICKEN used to compile the library.

**Comment by 0-8-15** [comment]
Hi,

looks like I did not (yet) receive the posting Caloan replied to.

I _guess_ this has to do with Ticket 1232
http://bugs.call-cc.org/ticket/1232

Please try the patch attached to that ticket.  (It's really a grave bug
in chicken which sooner or later hits anyway.  My changes just
exacerbated the chance to be bitten by it.

Am 12.01.2016 um 23:33 schrieb Caolan McMahon:
